version: '3.7'

services:
  appmongo:
    build: .
    restart: always
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    networks:
      - db-network
    depends_on:
      - db


  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: user_root
      POSTGRES_PASSWORD: pass_root
      POSTGRES_DB: projetinho
    ports:
      - 5433:5433
    volumes:
      - ./data_db/:/var/lib/postgresql/data/
    command: -p 5433
    networks:
      - db-network


networks:
    db-network:
      driver: bridge